using System;
using System.IO;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.YouTubeSync.Controllers;

/// <summary>
/// HTTP API controller that resolves a YouTube video ID to either a direct CDN redirect
/// or a DASH stream backed by a growing temporary file.
///
/// Endpoint: GET /YouTubeSync/resolve/{videoId}
///
/// The .strm files generated by <see cref="SyncService"/> point to this endpoint.
/// When a Jellyfin client initiates playback, it fetches this URL, which in turn
/// calls yt-dlp to obtain the best progressive stream URL or a DASH video/audio pair.
/// </summary>
[ApiController]
[Route("YouTubeSync")]
[Produces(MediaTypeNames.Application.Json)]
public class YouTubeSyncController : ControllerBase
{
    private readonly DashMergeCacheService _dashMergeCacheService;
    private readonly ResolveService _resolveService;
    private readonly YtDlpService _ytDlpService;
    private readonly ILogger<YouTubeSyncController> _logger;

    /// <summary>Initializes a new instance of the <see cref="YouTubeSyncController"/> class.</summary>
    public YouTubeSyncController(
        DashMergeCacheService dashMergeCacheService,
        ResolveService resolveService,
        YtDlpService ytDlpService,
        ILogger<YouTubeSyncController> logger)
    {
        _dashMergeCacheService = dashMergeCacheService;
        _resolveService = resolveService;
        _ytDlpService = ytDlpService;
        _logger = logger;
    }

    /// <summary>
    /// Resolves a YouTube video ID to either a direct CDN redirect or a DASH merge stream.
    /// Returns 503 when no compatible playback format is available.
    /// </summary>
    /// <param name="videoId">The YouTube video ID (e.g. dQw4w9WgXcQ).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>302 redirect, streamed MP4 response, or 503 if no compatible format is found.</returns>
    [HttpGet("resolve/{videoId}")]
    [ProducesResponseType(StatusCodes.Status302Found)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> ResolveVideo(string videoId, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(videoId) || videoId.Length > 32)
        {
            return BadRequest("Invalid video ID.");
        }

        _logger.LogInformation("Resolve request for video {VideoId}", videoId);

        var result = await _resolveService.ResolveAsync(videoId, cancellationToken).ConfigureAwait(false);
        if (result is null)
        {
            _logger.LogWarning(
                "No compatible playback format available for {VideoId}. Returning 503.",
                videoId);
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                $"No compatible progressive or DASH format found for video '{videoId}'.");
        }

        if (result.IsRedirect)
        {
            return Redirect(result.RedirectUrl!);
        }

        if (!result.IsDashMerge)
        {
            _logger.LogWarning("Resolve result for {VideoId} was neither redirect nor DASH merge.", videoId);
            return StatusCode(StatusCodes.Status503ServiceUnavailable, "Invalid playback result.");
        }

        var lease = await _dashMergeCacheService
            .AcquireAsync(videoId, result.DashVideoUrl!, result.DashAudioUrl!, HttpContext.RequestAborted)
            .ConfigureAwait(false);

        if (lease is null)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                "Failed to prepare the merged DASH file. Check the configured ffmpeg path or PATH.");
        }

        HttpContext.Response.OnCompleted(async () =>
        {
            await lease.DisposeAsync().ConfigureAwait(false);
        });

        _logger.LogInformation("Serving DASH merge for video {VideoId} from {MergedFilePath}", videoId, lease.FilePath);
        Response.Headers.CacheControl = "no-store";

        if (lease.IsComplete)
        {
            return PhysicalFile(lease.FilePath, "video/mp4", enableRangeProcessing: true);
        }

        return await StreamGrowingDashFileAsync(videoId, lease, HttpContext.RequestAborted).ConfigureAwait(false);
    }

    private async Task<IActionResult> StreamGrowingDashFileAsync(
        string videoId,
        DashMergeCacheService.DashMergeLease lease,
        CancellationToken cancellationToken)
    {
        Response.StatusCode = StatusCodes.Status200OK;
        Response.ContentType = "video/mp4";
        Response.Headers.CacheControl = "no-store";

        await using var input = new FileStream(
            lease.FilePath,
            FileMode.Open,
            FileAccess.Read,
            FileShare.ReadWrite | FileShare.Delete,
            81920,
            FileOptions.Asynchronous | FileOptions.SequentialScan);

        try
        {
            await Response.StartAsync(cancellationToken).ConfigureAwait(false);
            var buffer = new byte[81920];

            while (true)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var bytesRead = await input.ReadAsync(buffer.AsMemory(0, buffer.Length), cancellationToken)
                    .ConfigureAwait(false);
                if (bytesRead > 0)
                {
                    await Response.Body.WriteAsync(buffer.AsMemory(0, bytesRead), cancellationToken)
                        .ConfigureAwait(false);
                    await Response.Body.FlushAsync(cancellationToken).ConfigureAwait(false);
                    continue;
                }

                if (lease.MergeTask.IsCompleted)
                {
                    if (!await lease.MergeTask.ConfigureAwait(false))
                    {
                        _logger.LogWarning("Growing DASH merge failed before completion for video {VideoId}", videoId);
                    }

                    break;
                }

                await Task.Delay(200, cancellationToken).ConfigureAwait(false);
            }

            return new EmptyResult();
        }
        catch (OperationCanceledException)
        {
            _logger.LogInformation("Client disconnected while streaming growing DASH file for video {VideoId}", videoId);
            return new EmptyResult();
        }
    }

    /// <summary>
    /// Fetches metadata (title, description, thumbnail URL, type) for a YouTube channel or playlist URL.
    /// Called by the admin configuration UI to auto-populate source details.
    /// </summary>
    /// <param name="url">The YouTube channel or playlist URL.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A <see cref="SourceInfo"/> object, or 400/503 on error.</returns>
    [HttpGet("source-info")]
    [ProducesResponseType(typeof(SourceInfo), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> GetSourceInfo([FromQuery] string url, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return BadRequest("url query parameter is required.");
        }

        _logger.LogInformation("Source-info request for URL {Url}", url);

        var info = await _ytDlpService.GetSourceInfoAsync(url, cancellationToken).ConfigureAwait(false);
        if (info is null)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                "Failed to fetch source info from YouTube. Check that yt-dlp is installed and the URL is valid.");
        }

        return Ok(info);
    }
}

